version: "3.9"

services:
  db:
    image: mysql:8
    container_name: picsite_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: picsite
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    # 不映射端口，不挂卷，数据不会持久化
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 自动初始化表
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picsite_backend
    restart: always
    ports:
      - "5000:5000"   # 暴露后端端口
    depends_on:
      - db            # 确保数据库先启动
